# Generated by Django 2.2.13 on 2020-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0006_auto_20191125_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='model',
            field=models.CharField(choices=[('Profiles', 'Profiles'), ('Offerings', 'Offerings'), ('Transactions', 'Transactions'), ('Categories', 'Categories'), ('PSGs', 'PSGs'), ('PSG Through', 'PSG Through'), ('iOS Sessions', 'iOS Sessions'), ('Web Sessions', 'Web Sessions')], max_length=160, verbose_name='Name of model to import to'),
        ),
    ]
